### ISSUE TITLE
菜单渲染问题

### ISSUE THREAD

**Issue by fuyunwang** [buqiyuan/vite-vue3-admin#1]
请问如果我只有一个子菜单项的如何设置左侧列表只显示这个菜单项，不创建他的父级目录？
比如，系统看板菜单下只有一个子菜单项，所以我就不想显示这个系统看板了直接显示一个首页作为单独的菜单

**Comment by buqiyuan** [comment]
大概明白你的意思，可以的呀！
![image](https://user-images.githubusercontent.com/39730999/110409127-bf369180-80c1-11eb-8e88-75aee8f7c774.png)

**Comment by fuyunwang** [comment]
这个应该怎么改呀，或者改哪一步分可以实现

**Comment by ghost** [comment]
menuInfo.children?.length>1
<a-breadcrumb-item v-if="routeItem.children?.length!=1">

**Comment by fuyunwang** [comment]
谢谢

**Comment by ghost** [comment]
<a-breadcrumb-item v-if="routeItem.children?.length!=1">
