### ISSUE TITLE
echarts

### ISSUE THREAD

**Issue by xunnasu** [buqiyuan/vite-vue3-admin#12]
可以增加一些echarts 的图表的配置吗  还有表格中筛选功能 哈哈

**Comment by buqiyuan** [comment]
可以，后面看情况安排一个数据大屏⑧

**Comment by xunnasu** [comment]
好的呀  辛苦～ 现在大屏展示需求还是蛮多的 数据可视化嘛

**Comment by buqiyuan** [comment]
是的呀 所以可视化也是我下半年要深入学习的一个领域
