### ISSUE TITLE
generator-router 动态菜单父菜单redirect不生效

### ISSUE THREAD

**Issue by meguoe** [buqiyuan/vite-vue3-admin#19]
hi, buqiyuan，我看了generator-router的代码，其中有一个判断 if (item.type === 0) 同时 if (children?.length) 存在子项时，会把子项的第一个菜单的name作为父菜单的redirect参数，但使用过程中貌似不生效？

**Comment by buqiyuan** [comment]
🤔刚刚测试了下，好像只有`/report`这个路径有这个问题，尝试在vue-router源码搜了下 也没搜到和`report`相关的代码，暂时不确定是什么原因，如果你发现了也欢迎跟我分享~

**Comment by meguoe** [comment]
我这边在https://vite-vue3-admin.vercel.app试了一下，貌似其他的也不行，例如：
/dashboard   预期: /dashboard/welcome   结果：404
/demos   预期: /demos/custom-modal   结果：404
/sys/permission    预期: /sys/permission/user   结果：404
.....

调试了一下，感觉问题应该出在这里，filterRoutes 后layout.children 中只保留了菜单的路由，目录的路由都没有了
`
    const filterRoutes = router
      .getRoutes()
      .filter(
        (item) =>
          (!item.children.length || Object.is(item.meta?.hideChildrenInMenu, true)) &&
          !outsideLayout.some((n) => n.name === item.name),
      );
    removeRoute();
    layout.children = [...filterRoutes];
`
