### ISSUE TITLE
无法在Safari浏览器下访问页面

### ISSUE THREAD

**Issue by ChenKevinJanet** [buqiyuan/vite-vue3-admin#20]
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/98368942/180911703-744f33d8-f120-41a5-90d7-6f6570f357a1.png">

在Safari浏览器下访问，报语法错误
建议改成

<img width="1056" alt="image" src="https://user-images.githubusercontent.com/98368942/180917113-8a124f43-0895-4fe8-a03e-566d0aa5d000.png">

**Comment by ChenKevinJanet** [comment]
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/98368942/180911703-744f33d8-f120-41a5-90d7-6f6570f357a1.png">

**Comment by 1014156094** [comment]
无法在Safari浏览器下访问页面 +1

**Comment by buqiyuan** [comment]
谢谢反馈~
![image](https://user-images.githubusercontent.com/39730999/181065487-1483a812-aa35-487f-bcd6-db8e65635ebc.png)
下面这个应该更严谨一些
```js
'https:///github.com/buqiyuan//vite-vue3-admin/issues//20'.replace(/(https?:\/)|(\/)+/g, '$1$2')
```

**Comment by ChenKevinJanet** [comment]
👍
