### ISSUE TITLE
项目成功启动首页白屏

### ISSUE THREAD

**Issue by annihilationism** [buqiyuan/vite-vue3-admin#26]
<img width="512" alt="image" src="https://user-images.githubusercontent.com/35182117/191924230-d8938ace-e943-4823-b504-7c695d5a91a6.png">
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/35182117/191924274-dd818211-09b6-478b-ae74-13b752d05fa0.png">

项目成功启动后后白屏了

**Comment by buqiyuan** [comment]
控制台有报错信息吗

**Comment by annihilationism** [comment]
> 控制台有报错信息吗

<img width="766" alt="image" src="https://user-images.githubusercontent.com/35182117/191925792-913c245b-7095-4689-8440-198590adba29.png">
控制台没有报错信息

**Comment by annihilationism** [comment]
> 控制台有报错信息吗

仔细看了下控制台有报错，但是很快就被刷掉了，根本看不清报的错

**Comment by buqiyuan** [comment]
我本地没复现，没有详细的信息的话，我没办法确认问题

**Comment by annihilationism** [comment]
> 

![image](https://user-images.githubusercontent.com/35182117/191929907-d74db29d-387b-4d28-b562-cc55a2d3ff08.png)
<img width="932" alt="image" src="https://user-images.githubusercontent.com/35182117/191930010-c975edef-021b-4332-a1d8-13c2631b7546.png">
用手机拍的，有点模糊

**Comment by buqiyuan** [comment]
你本地node版本多少？最好是：node 16+，  pnpm安装依赖，浏览器Chrome90+

**Comment by annihilationism** [comment]
> 你本地node版本多少？最好是：node 16+， pnpm安装依赖，浏览器Chrome90+

Chrome 已是最新版本
版本 105.0.5195.125（正式版本） (x86_64)
cnpm@8.3.0
npm@8.19.1 
node@16.17.0
npminstall@6.5.1 
pnpm@7.11.0

**Comment by buqiyuan** [comment]
嗯~环境要求是满足的，但还是不能确定是什么问题

**Comment by annihilationism** [comment]
> 嗯~环境要求是满足的，但还是不能确定是什么问题

我换到 vue3-antd-admin 这个项目了，这个没问题

**Comment by chenyang48671155** [comment]
一样的问题
