### ISSUE TITLE
git clone https://github.com/buqiyuan/vite-vue3-admin

### ISSUE THREAD

**Issue by Square-y** [buqiyuan/vite-vue3-admin#27]
在命令行执行命令：
git clone https://github.com/buqiyuan/vite-vue3-admin
出现异常：
E:\go_code\multissh-master>git clone https://github.com/buqiyuan/vite-vue3-admin
Cloning into 'vite-vue3-admin'...
fatal: unable to access 'https://github.com/buqiyuan/vite-vue3-admin/': OpenSSL SSL_read: Connection was reset, errno 10054

**Comment by buqiyuan** [comment]
这应该是网络问题，挂个梯子吧
