### ISSUE TITLE
clone代码安装依赖后无法启动

### ISSUE THREAD

**Issue by QianShi-ffg** [buqiyuan/vite-vue3-admin#28]
## Bug report（问题描述）
从github拉下代码安装依赖后 直接运行就报错,重装了几次依赖都是一样的错

#### Screenshot or Gif（截图或动态图）
![image](https://user-images.githubusercontent.com/56419687/207499595-7293d556-1e5f-4b12-90dd-daaa2ea87101.png)

#### Other relevant information（格外信息）

- Your OS:
- Node.js version:
- packageManager:

**Comment by AuhNijGnahz** [comment]
一样的，我vite直接没反应

**Comment by buqiyuan** [comment]
我本地没复现，不过看着像是 `vite-plugin-mkcert` 插件的问题，我已经移除该插件了，可以更新试试

**Comment by QianShi-ffg** [comment]
去除后就好了
