### ISSUE TITLE
项目启动成功，但页面无法加载

### ISSUE THREAD

**Issue by lyt31024** [buqiyuan/vite-vue3-admin#29]
项目启动成功了，报了包依赖的问题，
访问页面的时候，页面也一直卡着，但控制台也没有报错。

1： pnpm install 一切正常。
2：pnpm serve 提示如下，但项目还是成功启动了。
Failed to resolve dependency: @vue/shared, present in 'optimizeDeps.include'
3：浏览器访问项目地址。

![KV YNK80%9ED)LMYZ)1MM%V](https://user-images.githubusercontent.com/64526046/212025545-7a049e57-ca23-4064-97ab-e9941e2967fb.png)

![GOGA7SUG$R((0XI@E@W6HLI](https://user-images.githubusercontent.com/64526046/212025735-0c9cedb7-b643-44eb-b0c6-628501e02d88.png)

- Your OS: win10
- Node.js 版本: v16.18.1
- packageManager: pnpm v7.18.2

**Comment by buqiyuan** [comment]
刚试了下，页面可以加载，就是首次加载会比较慢(特别是在Windows系统)，加载成功后，后续启动有缓存会快很多，慢的原因主要是因为 在开发环境下全量加载了 antdv，具体[配置在这](https://github.com/buqiyuan/vite-vue3-admin/blob/0e35e91ca262e26af3387f99fc6f389a1d9ee9be/vite.config.ts#L93-L117)，开发环境下全量加载 antdv 的理由主要是为了解决在切换路由时 如果新页面有新组件则会重新编译组件出现卡顿、重新加载页面的情况。
归根结底，慢的主要原因是在 less 编译的时间
