### ISSUE TITLE
运行时unplugin-vue-define-options报错

### ISSUE THREAD

**Issue by lampard-8** [buqiyuan/vite-vue3-admin#31]
[vite] Internal server error: unplugin-vue-define-options TypeError: Cannot read properties of undefined (reading 'scriptSetupAst')

**Comment by MrMingZhang** [comment]
me too

**Comment by zouyu01-sz** [comment]
tsconfig.json下配置：
"types": ["node", "vite/client", "unplugin-vue-define-options","unplugin-vue-define-options/macros-global"],

**Comment by YAGregor** [comment]
尝试了一下使用yarn安装依赖会产生这个错误，但是用pnpm不会，可能是小版本锁定的问题

**Comment by letear** [comment]
> tsconfig.json下配置： "types": ["node", "vite/client", "unplugin-vue-define-options","unplugin-vue-define-options/macros-global"],

It didn't work

**Comment by mohammadAthRumman** [comment]
upgrade unplugin-vue-define-options to 1.1.3
