### ISSUE TITLE
无法找到模块“vue-i18n”的声明文件

### ISSUE THREAD

**Issue by createi** [buqiyuan/vite-vue3-admin#35]
## Bug report（问题描述）

运行没有问题，但是i18n Ally 扩展 提示 没有找到文案
import from vue-i18n 的地方都是  无法找到模块“vue-i18n”的声明文件。

#### Other relevant information（格外信息）

- Your OS: window11
- Node.js version: 14.21.3
- packageManager: pnpm v 6.35.1

**Comment by chengazhen** [comment]
装个beta版本的 vueI18n, 插件仓库有这个issue, 作者还没有发版
