### ISSUE TITLE
本地运行超级慢，不知道啥原因

### ISSUE THREAD

**Issue by pamxy** [buqiyuan/vite-vue3-admin#5]
本地运行超级慢，不知道啥原因/(ㄒoㄒ)/~~

**Comment by buqiyuan** [comment]
啊这 😬可能是我配置有问题吧！vite版是附带的，配置这块可能还得再优化一下

**Comment by lpz1096** [comment]
确实有这个问题，打开页面加载很慢

**Comment by lpz1096** [comment]
多谢大佬的项目，学到了很多知识，从去年你发布gitee就关注你了，刚给你发了小红包买杯咖啡

**Comment by buqiyuan** [comment]
> 多谢大佬的项目，学到了很多知识，从去年你发布gitee就关注你了，刚给你发了小红包买杯咖啡

😁谢谢大兄弟支持！加载慢原因大概是像[这篇文章](https://www.cnblogs.com/hetaojs/p/15386371.html)分析的，优化的话，可能还是得像[vite官方文档(依赖预构建)](https://cn.vitejs.dev/guide/dep-pre-bundling.html#the-why)中所说的`将有许多内部模块的 ESM 依赖关系转换为单个模块，以提高后续页面加载性能`了

**Comment by buqiyuan** [comment]
@pamxy @lpz1096 已修复，重复刷新页面是antfu大佬的[unplugin-vue-components](https://github.com/antfu/unplugin-vue-components)问题，已替换为vite-plugin-style-import

**Comment by Meihualu-cc** [comment]
可是替换为vite-plugin-style-import还是很慢哎

**Comment by buqiyuan** [comment]
> 可是替换为vite-plugin-style-import还是很慢哎

(⊙o⊙)…有多慢呢？vite的主要优势在于开发时冷启动速度快，但是在首次启动时 按需编译的过程还是需要耗费一定时间的，首次启动时页面有十几秒的等待时间很正常，你看下network 请求mian.ts的耗时多久

**Comment by Meihualu-cc** [comment]
确实，我是首次加载页面很慢，但是好像不止十几秒，请求mian.ts耗时37s，感觉首次比umi慢，但是开发时冷启动确实快好多

**Comment by Meihualu-cc** [comment]
是的，是第一次启动很，但是好像不止几秒钟，但是第一次请求我开车时慢37秒，我觉得开个慢米，快了很多次

**Comment by Meihualu-cc** [comment]
> > 可是替换为vite-plugin-style-import还是很慢哎
> 
> (⊙o⊙)…有多慢呢？vite的主要优势在于开发时冷启动速度快，但是在首次启动时 按需编译的过程还是需要耗费一定时间的，首次启动时页面有十几秒的等待时间很正常，你看下network 请求mian.ts的耗时多久

请求mian.ts耗时37s，我就首次启动时页面加载慢，而且不止十几秒

**Comment by buqiyuan** [comment]
> 请求mian.ts耗时37s，我就首次启动时页面加载慢，而且不止十几秒

![image](https://user-images.githubusercontent.com/39730999/161202024-9608b760-b556-4a61-b8af-80d51c495f38.png)
(⊙o⊙)…那应该是你机器性能问题了 我本地都是在15s左右，你可以尝试启用`http2` 或 合理使用`import()`进行按需加载 看能否优化那么丢丢了

**Comment by meguoe** [comment]
> > > 可是替换为vite-plugin-style-import还是很慢哎
> > 
> > 
> > (⊙o⊙)…有多慢呢？vite的主要优势在于开发时冷启动速度快，但是在首次启动时 按需编译的过程还是需要耗费一定时间的，首次启动时页面有十几秒的等待时间很正常，你看下network 请求mian.ts的耗时多久
> 
> 请求mian.ts耗时37s，我就首次启动时页面加载慢，而且不止十几秒

在vite.config.ts -> optimizeDeps -> include 中加入常用的组件：
        'ant-design-vue/es/menu/style/css',
        'ant-design-vue/es/card/style/css',

**Comment by meguoe** [comment]
在vite.config.ts -> optimizeDeps -> include 中加入常用的组件：
'ant-design-vue/es/menu/style/css',
'ant-design-vue/es/card/style/css',
把常用的组件加入到预编译后，首次运行访问就很快了
