### ISSUE TITLE
左侧菜单超长隐藏

### ISSUE THREAD

**Issue by chivosss** [buqiyuan/vite-vue3-admin#6]
左侧菜单能否支持滚动条显示
![image](https://user-images.githubusercontent.com/44773971/148151480-093d3eb7-b0e0-446d-a1f7-c775b772ad4f.png)

**Comment by buqiyuan** [comment]
![image](https://user-images.githubusercontent.com/39730999/148331294-f93ac215-6af3-4ca4-9fec-92c12f705e9f.png)

找到menu.vue文件，把scoped注释掉就好了

**Comment by chivosss** [comment]
去掉就可以了
