### ISSUE TITLE
src的pubPath.ts文件和public的index.html是不是可以删除了呀？

### ISSUE THREAD

**Issue by Silentdoer** [buqiyuan/vite-vue3-admin#7]

**Comment by Silentdoer** [comment]
有些不用的没有用到的文件最好能清理下方便理解😂

**Comment by Silentdoer** [comment]
还有就是.env.development可以改成.development.env吗？dotenv的插件貌似基本上都是以.env为最后的后缀才能识别这种配置

**Comment by buqiyuan** [comment]
😂确实，有空清理一下，这个是vue-cli手动改成vite的，所以可能会有些残留文件，有空再清理一下，或者你也可以提个PR

**Comment by buqiyuan** [comment]
![image](https://user-images.githubusercontent.com/39730999/150994135-fd183137-faec-475f-a4fe-6821a7303fad.png)

关于.env文件，我是照着[官方示例](https://vitejs.cn/guide/env-and-mode.html#env-files)使用的，可以识别的，暂时也没遇到什么问题

**Comment by Silentdoer** [comment]
好的，再问下，为啥tsconfig.json里一直报cannot find type definition file for shims呀？

**Comment by buqiyuan** [comment]
🤔我本地没有这个问题，感觉是不是依赖没装好，找不到相关的类型声明文件

**Comment by Silentdoer** [comment]
> 🤔我本地没有这个问题，感觉是不是依赖没装好，找不到相关的类型声明文件

好的，我再找找问题。
