### ISSUE TITLE
路由问题

### ISSUE THREAD

**Issue by Sunny-liaokai** [buqiyuan/vite-vue3-admin#8]
SyntaxError: The requested module '/node_modules/.vite/xlsx.js?v=49175fa3' does not provide an export named 'default' '路由错误'
有些路由点击报这个错误，是因为vite的版本原因吗

**Comment by buqiyuan** [comment]
xlsx.js升级到新版本后没有默认导出的问题，[已修复](https://github.com/buqiyuan/vite-vue3-admin/commit/a0b0fc8c78e1cf75e5ed7e48aee03dc7ce364db4)
