### ISSUE TITLE
为啥和 vue-vben-admin 那么像，有什么关系？有什么区别么？

### ISSUE THREAD

**Issue by 1014156094** [buqiyuan/vite-vue3-admin#9]
我看 UI 界面和代码结构都很像 https://github.com/vbenjs/vue-vben-admin/blob/main/README.zh-CN.md 是参考 vue-vben-admin 的么？有什么关系？有什么区别？

**Comment by wodexintailuan** [comment]
vben那个好复杂,好多东西,  我就想简单写个后台而已...

**Comment by buqiyuan** [comment]
没有关系，有一些参考的成分，话说同一个UI库出来的界面不都差不多吗？后台管理系统不都是大同小异吗？你确定你看完项目进行对比了？

**Comment by 1014156094** [comment]
好的，谢谢作者解答

**Comment by buqiyuan** [comment]
> 好的，谢谢作者解答

优秀的框架都值得我们去学习，vben-admin是非常优秀的后台管理系统，我在写这个项目的时候，也会去看别的优秀项目，学习别人的优点，但不是说照搬别人代码

**Comment by 1014156094** [comment]
> > 好的，谢谢作者解答
> 
> 优秀的框架都值得我们去学习，vben-admin是非常优秀的后台管理系统，我在写这个项目的时候，也会去看别的优秀项目，学习别人的优点，但不是说照搬别人代码
其实我觉得你这个比 vben-admin 好，感觉 vben-admin 过度封装了接手难度和维护成本高，哈哈哈

**Comment by 1014156094** [comment]
> > 好的，谢谢作者解答
> 
> 优秀的框架都值得我们去学习，vben-admin是非常优秀的后台管理系统，我在写这个项目的时候，也会去看别的优秀项目，学习别人的优点，但不是说照搬别人代码

其实我觉得你这个比 vben-admin 好，感觉 vben-admin 过度封装了接手难度和维护成本高，哈哈哈
